c53

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,7 +10,7 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     permissions:
-      contents: write  # potrzebne do publikowania na gh-pages
+      contents: write
 
     steps:
       - name: Checkout repository
@@ -27,6 +27,12 @@ jobs:
 
       - name: Build app
         run: npm run build
+        env:
+          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
+
+      - name: Debug — show build folder content
+        if: always()
+        run: ls -la ./build || echo "Build folder not found"
 
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v4
